[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mappero"
version = "0.1"
description = "A versatile tool for 3D capture, mapping, and reconstruction."
authors = [{ name = "Tarek BOUAMER", email = "tarekbouamer1788@gmail.com" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "h5py",
    "numpy<2.0",
    "omegaconf>=2.1",
    "click>=8.0",
    "loguru>=0.5.3",
    "open3d>=0.13.0",
    "imm @ git+https://github.com/Tarekbouamer/imm.git@dev#egg=imm", 
]

[tool.setuptools.packages.find]
include = ["mappero*"]

[project.urls]
"Homepage" = "https://github.com/Tarekbouamer/mappero"
"Documentation" = "https://github.com/Tarekbouamer/mappero/wiki"
"Source" = "https://github.com/Tarekbouamer/mappero"
"Tracker" = "https://github.com/Tarekbouamer/mappero/issues"

[project.entry-points.console_scripts]
mappero-colmap = "mappero.modules.colmap:run_colmap"
mappero-pycolmap = "mappero.modules.pycolmap:run_pycolmap"
mappero-glomap = "mappero.modules.glomap:run_glomap"
mappero-opensfm = "mappero.modules.opensfm:run_opensfm"
mappero-vis = "mappero.visualization.vis3d:run_vis"
mappero-gui = "mappero.visualization.gui:run_gui"
